GRIDSIZE = 100
TICKS_PER_UPDATE = 5
UPDATES_PER_SECOND = 10
BULLET_SPEED = 0.5
PLAYER_SPEED = 0.2
FALL_SPEED = 1
PLAYER_SIZE = { x: 5.5, y: 6.5 }

module.exports = {
  GRIDSIZE,
  TICKS_PER_UPDATE,
  UPDATES_PER_SECOND,
  BULLET_SPEED,
  PLAYER_SPEED,
  PLAYER_SIZE,
  FALL_SPEED
}