GRIDSIZE = 100
TICKS_PER_UPDATE = 1
UPDATES_PER_SECOND = 10
BULLET_SPEED = 2.5
PLAYER_SPEED = 1

module.exports = {
  GRIDSIZE,
  TICKS_PER_UPDATE,
  UPDATES_PER_SECOND,
  BULLET_SPEED,
  PLAYER_SPEED
}