GRIDSIZE = 100
TICKS_PER_UPDATE = 10
UPDATES_PER_SECOND = 5
BULLET_SPEED = 0.5
PLAYER_SPEED = 0.2

module.exports = {
  GRIDSIZE,
  TICKS_PER_UPDATE,
  UPDATES_PER_SECOND,
  BULLET_SPEED,
  PLAYER_SPEED
}